# Generated by Django 6.0.3 on 2026-03-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="XRayAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="xrays/")),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("findings", models.TextField(blank=True, default="")),
                ("impression", models.TextField(blank=True, default="")),
                ("pathologies", models.JSONField(default=list)),
                ("recommendations", models.TextField(blank=True, default="")),
                ("confidence_score", models.FloatField(default=0)),
                (
                    "xai_image",
                    models.ImageField(blank=True, null=True, upload_to="xai/"),
                ),
                ("raw_report", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Analyse X-Ray",
                "verbose_name_plural": "Analyses X-Ray",
                "ordering": ["-date"],
            },
        ),
    ]
