# Generated by Django 6.0.3 on 2026-04-05 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xrayanalysis',
            options={'ordering': ['-date'], 'permissions': [('view_all_analyses', 'Can view all analyses'), ('export_analysis', 'Can export analysis')], 'verbose_name': 'Analyse X-Ray', 'verbose_name_plural': 'Analyses X-Ray'},
        ),
        migrations.AlterField(
            model_name='xrayanalysis',
            name='confidence_score',
            field=models.FloatField(default=0, help_text='AI model confidence score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='xrayanalysis',
            name='date',
            field=models.DateTimeField(auto_now_add=True, help_text='Analysis creation timestamp'),
        ),
        migrations.AlterField(
            model_name='xrayanalysis',
            name='findings',
            field=models.TextField(blank=True, default='', help_text='Detailed radiological findings from AI analysis'),
        ),
        migrations.AlterField(
            model_name='xrayanalysis',
            name='image',
            field=models.ImageField(help_text='Original X-ray image file', upload_to='xrays/'),
        ),
        migrations.AlterField(
            model_name='xrayanalysis',
            name='impression',
            field=models.TextField(blank=True, default='', help_text='Clinical impression summary'),
        ),
        migrations.AlterField(
            model_name='xrayanalysis',
            name='pathologies',
            field=models.JSONField(default=list, help_text='List of detected pathological conditions'),
        ),
        migrations.AlterField(
            model_name='xrayanalysis',
            name='raw_report',
            field=models.TextField(blank=True, default='', help_text='Raw report data from AI model'),
        ),
        migrations.AlterField(
            model_name='xrayanalysis',
            name='recommendations',
            field=models.TextField(blank=True, default='', help_text='Clinical recommendations and follow-up'),
        ),
        migrations.AlterField(
            model_name='xrayanalysis',
            name='xai_image',
            field=models.ImageField(blank=True, help_text='Explainable AI visualization (Grad-CAM heatmap)', null=True, upload_to='xai/'),
        ),
        migrations.AddIndex(
            model_name='xrayanalysis',
            index=models.Index(fields=['-date'], name='api_xrayana_date_0f49c7_idx'),
        ),
    ]
