# Generated by Django 5.2.12 on 2026-04-10 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('api', '0002_alter_xrayanalysis_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='xrayanalysis',
            name='doctor',
            field=models.ForeignKey(blank=True, help_text='Doctor who created the analysis', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xray_analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='xrayanalysis',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='Patient associated with the analysis', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xray_analyses', to='accounts.patientprofile'),
        ),
    ]
